// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbEJElgY8zYR7HwPtkssLCW2h-RtOe7X8',
    appId: '1:350355068799:web:18d4b70cb1daa7f16bac4a',
    messagingSenderId: '350355068799',
    projectId: 'test-e61bd',
    authDomain: 'test-e61bd.firebaseapp.com',
    storageBucket: 'test-e61bd.appspot.com',
    measurementId: 'G-RNK25TS22C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXO7_gnZ2-pJpmZnLSWXJObDjAW1jzdCk',
    appId: '1:350355068799:android:ec7a14a1a042234e6bac4a',
    messagingSenderId: '350355068799',
    projectId: 'test-e61bd',
    storageBucket: 'test-e61bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRHiDgkJzvGmw6nOdVAyB7N4Tnuoy6W2o',
    appId: '1:350355068799:ios:0748e15a7d3891666bac4a',
    messagingSenderId: '350355068799',
    projectId: 'test-e61bd',
    storageBucket: 'test-e61bd.appspot.com',
    iosBundleId: 'com.google.firebase.kapildev.demo',
  );
}
